# Generated by Django 4.2.1 on 2023-07-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_produto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Producto',
        ),
    ]
