# Generated by Django 4.2.1 on 2023-07-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_boleta',
            old_name='nombre_producto',
            new_name='id_producto',
        ),
    ]
